version: '3.8'

services:
  opensim:
    build:
      context: ./01-opensim
    container_name: opensim_server
    depends_on:
      - mysql
    ports:
      - "9000:9000/udp"  # Puerto para conexiones del cliente
      - "8002:8002"      # Puerto para el Grid
    volumes:
      - ./01-opensim/core:/opensim
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - REGION_NAME=${REGION_NAME}
      - REGION_UUID=${REGION_UUID}
      - REGION_LOCATION=${REGION_LOCATION}
      - REGION_PORT=${REGION_PORT}
    restart: unless-stopped
    networks:
      - opensim-net

  mysql:
    image: mysql:5.7  # Usar imagen oficial para evitar inconsistencias
    container_name: opensim_mysql
    ports:
      - "3315:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    networks:
      - opensim-net

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - opensim-net

volumes:
  mysql_data:

networks:
  opensim-net:
